### ISSUE TITLE
[BUG] Maybe a typo in base.py

### ISSUE THREAD

**Issue by LeiWang1999** [ModelCloud/GPTQModel#415] opened 2024-10-08 09:04 UTC
Hi all, looks like the `SUPPORTED_SHARDS` should be `SUPPORTS_SHARDS`

```python
  File "/dataHDD16T/v-leiwang3/GPTQModel/debug/rebuttal_ppl.py", line 87, in <module>
    
  File "/dataHDD16T/v-leiwang3/GPTQModel/debug/rebuttal_ppl.py", line 64, in main
    model = GPTQModel.from_pretrained(pretrained_model_id, quantize_config)
  File "/dataHDD16T/v-leiwang3/GPTQModel/gptqmodel/models/base.py", line 686, in save_quantized
    if not self.qlinear_kernel.SUPPORTED_SHARDS and max_shard_size is not None:
AttributeError: type object 'TritonV2QuantLinear' has no attribute 'SUPPORTED_SHARDS'. Did you mean: 'SUPPORTS_SHARDS'?
```

**Comment by Qubitium** [comment] 2024-10-08 09:45
@ZX-ModelCloud  Looks like the latest naming refractor missed a spot.

**Comment by Qubitium** [comment] 2024-10-08 09:56
@LeiWang1999  Should be fixed in https://github.com/ModelCloud/GPTQModel/pull/417. We are running CI on master now to make sure we didn't miss other regressions.

**Comment by Qubitium** [comment] 2024-10-08 10:43
There are more regressions. CI has found that the in/out features padding fix is causing more quant linear types to fail.

**Comment by Qubitium** [comment] 2024-10-08 14:15
Closing issue as all CI passing with latest master.

**Closed by Qubitium** 2024-10-08 14:15 UTC
Labels: bug
