### ISSUE TITLE
[COMPAT] vLLM does not support quantized MoE except for Mixtral (i.e. 4bit DeepSeek-V2 not supported)

### ISSUE THREAD

**Issue by Xu-Chen** [ModelCloud/GPTQModel#124] opened 2024-06-30 11:57 UTC
Using vllm to infer the deepseek model encountered an error

```
[rank0]:     self.mlp = DeepseekV2MoE(config=config, quant_config=quant_config)
[rank0]:   File "/home/root/.local/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 113, in __init__
[rank0]:     self.pack_params()
[rank0]:   File "/home/root/.local/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 135, in pack_params
[rank0]:     w1.append(expert.gate_up_proj.weight)
[rank0]:   File "/home/root/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'MergedColumnParallelLinear' object has no attribute 'weight'. Did you mean: 'qweight'?
```

**Comment by Qubitium** [comment] 2024-06-30 12:41
@Xu-Chen  Please share your `config.json` and `quantize_config.json` so I can check the specs of your quantized model.

**Comment by Xu-Chen** [comment] 2024-06-30 12:45
> @Xu-Chen Please share your `config.json` and `quantize_config.json` so I can check the specs of your quantized model.

config.json
```
{
  "_name_or_path": "./DeepSeek-V2-Chat",
  "architectures": [
    "DeepseekV2ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "attn_implementation": "flash_attention_2",
  "auto_map": {
    "AutoConfig": "configuration_deepseek.DeepseekV2Config",
    "AutoModel": "modeling_deepseek.DeepseekV2Model",
    "AutoModelForCausalLM": "modeling_deepseek.DeepseekV2ForCausalLM"
  },
  "aux_loss_alpha": 0.001,
  "bos_token_id": 100000,
  "eos_token_id": 100001,
  "ep_size": 1,
  "first_k_dense_replace": 1,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 12288,
  "kv_lora_rank": 512,
  "max_position_embeddings": 163840,
  "model_type": "deepseek_v2",
  "moe_intermediate_size": 1536,
  "moe_layer_freq": 1,
  "n_group": 8,
  "n_routed_experts": 160,
  "n_shared_experts": 2,
  "norm_topk_prob": false,
  "num_attention_heads": 128,
  "num_experts_per_tok": 6,
  "num_hidden_layers": 60,
  "num_key_value_heads": 128,
  "pretraining_tp": 1,
  "q_lora_rank": 1536,
  "qk_nope_head_dim": 128,
  "qk_rope_head_dim": 64,
  "quantization_config": {
    "bits": 4,
    "checkpoint_format": "gptq",
    "damp_percent": 0.01,
    "desc_act": false,
    "group_size": 32,
    "lm_head": false,
    "meta": {
      "quantizer": "gptqmodel:0.9.1"
    },
    "model_file_base_name": null,
    "model_name_or_path": null,
    "quant_method": "gptq",
    "static_groups": false,
    "sym": true,
    "true_sequential": false
  },
  "rms_norm_eps": 1e-06,
  "rope_scaling": {
    "beta_fast": 32,
    "beta_slow": 1,
    "factor": 40,
    "mscale": 0.707,
    "mscale_all_dim": 0.707,
    "original_max_position_embeddings": 4096,
    "type": "yarn"
  },
  "rope_theta": 10000,
  "routed_scaling_factor": 16.0,
  "scoring_func": "softmax",
  "seq_aux": true,
  "tie_word_embeddings": false,
  "topk_group": 3,
  "topk_method": "group_limited_greedy",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.41.2",
  "use_cache": true,
  "v_head_dim": 128,
  "vocab_size": 102400
}
```

quantize_config.json
```
{
  "bits": 4,
  "group_size": 32,
  "desc_act": false,
  "static_groups": false,
  "sym": true,
  "lm_head": false,
  "damp_percent": 0.01,
  "true_sequential": false,
  "model_name_or_path": "./DeepSeek-V2-Chat-gptq-int4",
  "model_file_base_name": "model",
  "quant_method": "gptq",
  "checkpoint_format": "gptq",
  "meta": {
    "quantizer": "gptqmodel:0.9.1"
  }
}
```

**Comment by Qubitium** [comment] 2024-06-30 12:49
@Xu-Chen  To confirm, did you have inference problem with `GPTQMode.from_quantized()` too or is the inference issue localized to vLLM?

**Comment by Xu-Chen** [comment] 2024-06-30 12:52
> @Xu-Chen To confirm, did you have inference problem with `GPTQMode.from_quantized()` too or is the inference issue localized to vLLM?
 The inference issue localized to vLLM. I will try  `GPTQMode.from_quantized()` .

**Comment by Qubitium** [comment] 2024-07-03 11:27
Ref: https://github.com/vllm-project/vllm/issues/5343#issuecomment-2154882419

@Xu-Chen  vllm currently does not support quantized MoE models except Mixtral.

**Comment by Xu-Chen** [comment] 2024-07-03 13:11
> Ref: [vllm-project/vllm#5343 (comment)](https://github.com/vllm-project/vllm/issues/5343#issuecomment-2154882419)
> 
> @Xu-Chen vllm currently does not support quantized MoE models except Mixtral.

I try GPTQMode.from_quantized()，but the model's output is wrong, eg "GPTQModel is !!!!!!!!!!!!!!!!!!"

**Comment by Qubitium** [comment] 2024-07-03 15:18
What calibration sataset and size of calib data did you use? Also please using something other than GPTQModel is... as prompt test since it would just hallucinate on unknown info.

**Comment by Xu-Chen** [comment] 2024-07-20 11:55
> What calibration sataset and size of calib data did you use? Also please use something other than "GPTQModel is..." as prompt test since it would just hallucinate on unknown info.

Sorry to bother you. I tried the example from [DeepSeek-V2-Chat-0628-gptq-4bit](https://huggingface.co/ModelCloud/DeepSeek-V2-Chat-0628-gptq-4bit).  Got the following results.  Is there something wrong?  GPTQModel version：0.9.9.dev0.
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO - Compatibility: converting `checkpoint_format` from `gptq` to `gptq_v2`.
适应适应"(适应 aperspce"(a apapersapersapersapersapersapersp'apersaperspapersaperspapersapersp适应'"(apers"(适应.

apers"(aperspapersp.,苦瓜适应, .apers"(适应papers"(papersapersp.
apers"(apers
apersp.
.适应"(apers.
apersp.
apersapersapersp..apers"(适应"( apers"(.apersp.
apers笼
```

**Comment by LRL-ModelCloud** [comment] 2024-07-22 01:48
@Xu-Chen Can you share your test prompt and test examples?

**Comment by Xu-Chen** [comment] 2024-07-22 05:58
@LRL-ModelCloud  Thanks for  your reply. Only the model path was modified，transformers 4.24.4, gptqmode 0.9.9.dev0+cu121 （install form source）， 4*A800.
I will re-download the model and continue testing.
```
import torch
from transformers import AutoTokenizer, GenerationConfig
from gptqmodel import GPTQModel
model_name = "/path/to/nodel" #  Only the model path was modified
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
# `max_memory` should be set based on your devices
max_memory = {i: "75GB" for i in range(2)}
# `device_map` cannot be set to `auto`
model = GPTQModel.from_quantized(model_name, trust_remote_code=True, device_map="sequential", max_memory=max_memory, torch_dtype=torch.float16, attn_implementation="eager")

model.generation_config = GenerationConfig.from_pretrained(model_name)
model.generation_config.pad_token_id = model.generation_config.eos_token_id

messages = [
    {"role": "user", "content": "Write a piece of quicksort code in C++"}
]
input_tensor = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")
outputs = model.generate(input_ids=input_tensor.to(model.device), max_new_tokens=100)
result = tokenizer.decode(outputs[0][input_tensor.shape[1]:], skip_special_tokens=True)
print(result)
```

The log is as follows
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO - Compatibility: converting `checkpoint_format` from `gptq` to `gptq_v2`.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:100001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
适应适应"(适应适应 rebound"(适应 适应.

适应"(2apers. 笼.适应.apersapersapers.apers"(apers.apers"(适应"(适应.apers"(适应"(apers"(.apers2apers.apers2apers.笼.papers.
apers"(apers"("(适应. apers"("(apers. .2适应.2apers"("("(apers"(适应"(."(.apers"(. apers"(. rebound.,,opapers
```

**Comment by LRL-ModelCloud** [comment] 2024-07-22 06:47
@Xu-Chen I tested using 2 * A100, transformers 4.42.4, and gptqmode 0.9.9.dev and obtained normal inference results:
```python
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
Certainly! Below is an implementation of the Quicksort algorithm in C++:

```cpp
#include <iostream>
#include <vector>

// Function to partition the array and return the pivot index
int partition(std::vector<int>& arr, int low, int high) {
    int pivot = arr[high]; // Pivot element
    int i = low - 1; // Index of smaller element

    for (int j =

```

I noticed you are using 4 * A800, but `max_memory = {i: '75GB' for i in range(2)}`, which affects `device_map='sequential'`. Could you fix this issue and try again?

**Comment by Xu-Chen** [comment] 2024-07-22 06:54
> @Xu-Chen I tested using 2 * A100, transformers 4.42.4, and gptqmode 0.9.9.dev and obtained normal inference results:
> 
> ```python
> The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
> Certainly! Below is an implementation of the Quicksort algorithm in C++:
> 
> ```cpp
> #include <iostream>
> #include <vector>
> 
> // Function to partition the array and return the pivot index
> int partition(std::vector<int>& arr, int low, int high) {
>     int pivot = arr[high]; // Pivot element
>     int i = low - 1; // Index of smaller element
> 
>     for (int j =
> ```
> 
> I noticed you are using 4 * A800, but `max_memory = {i: '75GB' for i in range(2)}`, which affects `device_map='sequential'`. Could you fix this issue and try again?

Yes,  try max_memory = {i: '75GB' for i in range(4)}

**Comment by Qubitium** [comment] 2024-07-22 06:57
@Xu-Chen Confirmed issue fixed? If so, I will close this issue as completed.

**Closed** 2024-07-22 07:03 UTC
Labels: bug

**Comment by logesh13** [comment] 2025-11-14 06:07
Hi @Xu-Chen, How did you  resolve this issue 

"[rank0]: AttributeError: 'MergedColumnParallelLinear' object has no attribute 'weight'. Did you mean: 'qweight'?"

I hope somehow you have resolved this issue, May I know How did you resolve that ?

I am currently using Deepseek MOE Quantized model ( INT8 W8A16 ), I am facing this same error, It will be helpful if you help me to resolve this issue.

If you need more details please let me know, I'll paste the detailed information.
